apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-server
  namespace: test-inference
  labels:
    k8s-app: agent-server
spec:
  selector:
    matchLabels:
      k8s-app: agent-server
  template:
    metadata:
      labels:
        k8s-app: agent-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: usage
                    operator: In
                    values:
                      - offline-debug
      containers:
        - name: agent-server
          image: harbor.58corp.com/ailab/agent/server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: 2048Mi
              cpu: 1000m
            requests:
              cpu: 200m
              memory: 1024Mi
          volumeMounts:
            - name: cuda
              mountPath: /usr/local/cuda/
          env:
            - name: Hostname
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPRING_PROFILES_ACTIVE
              value: test
      volumes:
        - name: cuda
          hostPath:
            path: /usr/local/cuda/
