apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-server
  namespace: test-inference
  labels:
    k8s-app: agent-client
spec:
  selector:
    matchLabels:
      k8s-app: agent-client
  template:
    metadata:
      labels:
        k8s-app: agent-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpu/type
                    operator: In
                    values:
                      - P40
      containers:
        - name: agent-client
          image: harbor.58corp.com/ailab/agent/client:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: 2048Mi
              cpu: 1000m
            requests:
              cpu: 200m
              memory: 1024Mi
          volumeMounts:
            - name: cuda
              mountPath: /usr/local/cuda/
          env:
            - name: LOCAL_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: filename
              value: /usr/local/cuda/version.json
            - name: Agent_Server
              value: http://agent-server:8888
      volumes:
        - name: cuda
          hostPath:
            path: /usr/local/cuda/
